# Generated by Django 4.0.4 on 2022-07-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='short_name',
            field=models.CharField(default='-', max_length=10, verbose_name='Короткое наименование станции'),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_name',
            field=models.CharField(default='-', max_length=10, verbose_name='Короткое наименование установки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Полное имя события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Короткое имя события'),
        ),
    ]
